# `torch.nn.functional`

If you've combed through the PyTorch docs, you might notice that many utilities are implemented as both a class and a function. 

For example, the sigmoid can be implemented as either a class:


In [2]:
import torch

sigmoid = torch.nn.Sigmoid()
sigmoid(torch.tensor([[1, 2, 3]]))

tensor([[0.7311, 0.8808, 0.9526]])

Or functionally from the `torch.nn.functional` module, which is canonically imported as `F`, as shown below:

In [3]:
import torch.nn.functional as F

F.sigmoid(torch.tensor([[1, 2, 3]]))

/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[0.7311, 0.8808, 0.9526]])

### Why not just be consistent and keep everything as a class?

As you can see, the class implementation requires an extra line of code.

### Why not just be consistent and make everything a function?

Many objects require an internal state that needs to be tracked and persisted.
For example, neural network layers require parameters to be stored between passing different examples through the same layer.
In Python storing internal object states is typically done by creating an instance of a class, which can then store them as attributes of that instance.

Utilities that can be implemented as functions on the other hand, require no internal parameters - the outputs are purely a function of their input. 

For example, the sigmoid function will always produce the same output, given the same input. In contrast, the forward pass through a linear neural network layer will produce a different output dependent on its current parameterisation, which will change during training.


## Use cases

The most common things you will see `torch.nn.functional` used for are:
- Activation functions
- Loss functions
Which typically have no internal state.

### Activation functions
One common use of torch.nn.functional is applying activation functions to tensors.

#### ReLU
F.relu applies the rectified linear unit (ReLU) function elementwise to the input tensor.


In [4]:
input = torch.tensor([-1.0, 1.0, 0.0])
output = F.relu(input)
print(output)  # prints tensor([0.0, 1.0, 0.0])


tensor([0., 1., 0.])


#### Sigmoid
F.sigmoid applies the sigmoid function elementwise to the input tensor.


In [5]:

input = torch.tensor([-1.0, 1.0, 0.0])
output = F.sigmoid(input)
print(output)  # prints tensor([0.2689, 0.7311, 0.5])

tensor([0.2689, 0.7311, 0.5000])


#### Tanh
F.tanh applies the hyperbolic tangent function elementwise to the input tensor.

In [6]:

input = torch.tensor([-1.0, 1.0, 0.0])
output = F.tanh(input)
print(output)  # prints tensor([-0.7616, 0.7616, 0.0])

tensor([-0.7616,  0.7616,  0.0000])


/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


### Loss functions
Another common use of torch.nn.functional is computing loss functions.

#### Binary cross entropy
F.binary_cross_entropy computes the binary cross entropy loss. This loss is often used for binary classification tasks.


In [7]:
# input shape: (batch_size, num_classes)
input = torch.tensor([[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]])

# target shape: (batch_size, num_classes)
target = torch.tensor([[1.0, 0.0], [1.0, 0.0], [1.0, 0.0]])

loss = F.binary_cross_entropy(input, target)
print(loss)  # prints tensor(1.4133)

tensor(100.)


### Cross entropy
F.cross_entropy computes the cross entropy loss. This loss is often used for multi-class classification tasks.


In [8]:
# input shape: (batch_size, num_classes)
input = torch.tensor([[0.0, 1.0, 2.0], [0.0, 1.0, 2.0], [0.0, 1.0, 2.0]])

# target shape: (batch_size)
target = torch.tensor([1, 1, 0])

loss = F.cross_entropy(input, target)
print(loss)  # prints tensor(1.7409)

tensor(1.7409)


## Key Takeaways
- The functional implementations are stored in a module named `torch.nn.functional`.
- It is a module containing a large number of functions related to implementing neural networks. 
- "Functional" means that the utilities can be implemented as functions rather than classes.